### ISSUE TITLE
"./data" includes invalid characters

### ISSUE THREAD

**Issue by TheNomad11** [MoriTanosuke/wallabag-docker#2]
When running 

`docker run --rm -p 8080:80 -v ./data:/var/www/wallabag/data moritanosuke/wallabag-docker`

I get

`Error response from daemon: create ./data: "./data" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed`

**Comment by MoriTanosuke** [comment]
Try this

    docker run --rm -p 8080:80 -v $(pwd)/data:/var/www/wallabag/data moritanosuke/wallabag-docker

**Comment by MoriTanosuke** [comment]
@TheNomad11 Did you have a change to try the command?

**Comment by TheNomad11** [comment]
Hi and thanks for your answer. Before I try it: Will it be possible to have Wallabag running in a non-root  directory as f ex www.domain.com/wallabag/ ? It seems this is not so easy with docker? I'd like to use this domain for other stuff as well

**Comment by MoriTanosuke** [comment]
I tried to do that, but I found a lot of issues around it. Previously it wasn't even possible to run wallabag outside a container with a different base URL but I think that got fixed.

I want to run wallabag on my domain in a subdirectory as well, but I still cannot do so. I have to use a forwarded port on my domain instead of a subdirectory. I opened an issue https://github.com/wallabag/wallabag/issues/2273 a while ago, but it doesn't seem possible. Maybe I should give it another try with the current version.

**Comment by TheNomad11** [comment]
Without docker I was able to install it in a different directory, I just made it yesterday with this guide mostly https://got-tty.org/installation-von-wallabag-auf-debian-jessie but it would be better if it was possible with Docker, the standard installation process is a big mess, poorly documented, not userfriendly at all, directed mostly at geeks
